import Head from 'next/head'
import Footer from '../components/Footer'
import Navbar from '../components/Navbar'
import Hero from '../sections/Hero'
import Tagline from '../sections/Tagline'
import Tentang from '../sections/Tentang'

export default function Home() {
    return (
        <>
            <Head>
                <title>Tektik Website</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <Navbar />
                <Hero />
                <Tentang />
                <Tagline/>
                <Footer />
            </main>
        </>
    )
}
